Add tests that run the test images through metar.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -68,38 +68,6 @@ function testCmd() {
   exit
 }
 
-function cleanCmd() {
-
-  # Delete files generated by dot.
-  rm -f metar.deps"
-  rm -f metar/metar.deps"
-  rm -f metar/metar.dot"
-  rm -f metar/my.dot"
-  rm -f metar/metar.png"
-  rm -f testfiles.txt"
-  rm -f docfiles.txt"
-  rm -f names.txt"
-
-  # Delete files generated by coverage.
-  rm -f coverage.info"
-  rm -fr metar/coverage"
-
-  rm -f docs/*.json"
-
-  # Delete unneeded files in bin folder.
-  rm -f bin/test/test_*"
-  rm -f bin/metar*"
-  rm -f bin/metar.so*"
-
-  # Delete ~ files
-  find . -type f -name \*~ -delete
-
-  rm -f readme.html"
-  rm -f tshell.txt"
-  rm -f .DS_Store"
-  rm -f docs/.DS_Store"
-}
-
 function docsCmd() {
   # Build all the docs.
 
@@ -169,6 +137,61 @@ function dotCmd() {
 
 }
 
+function sanityCmd() {
+  # Run metar on the test files.
+
+  # Check the version number.
+  versionNum=$(bin/linux/metar -v)
+  if [[ ! "$versionNum" == "0.1.26" ]]; then
+    echo "Invalid version number: $versionNum"
+    exit
+  fi
+
+  # Check the help message.
+  helpFile=help.txt
+  bin/linux/metar > $helpFile
+  if ! diff $helpFile testfiles/$helpFile >/dev/null 2>&1; then
+    echo "Invalid help message."
+    exit
+  fi
+  rm $helpFile
+
+  # Check the jpg output
+  jpgOutputFile=jpg-output.txt
+  bin/linux/metar testfiles/image.jpg > $jpgOutputFile
+  if ! diff $jpgOutputFile testfiles/$jpgOutputFile >/dev/null 2>&1; then
+    echo "Invalid jpg output."
+    exit
+  fi
+  rm $jpgOutputFile
+
+  # Check the jpg json output
+  jpgJsonFile=jpg-output.json
+  bin/linux/metar -j testfiles/image.jpg > $jpgJsonFile
+  if ! diff $jpgJsonFile testfiles/$jpgJsonFile >/dev/null 2>&1; then
+    echo "Invalid jpg json output."
+    exit
+  fi
+  rm $jpgJsonFile
+
+  # Check the tiff output
+  tiffOutputFile=tiff-output.txt
+  bin/linux/metar testfiles/image.tif > $tiffOutputFile
+  if ! diff $tiffOutputFile testfiles/$tiffOutputFile >/dev/null 2>&1; then
+    echo "Invalid tiff output."
+    exit
+  fi
+  rm $tiffOutputFile
+
+  # Check the dng output
+  dngOutputFile=dng-output.txt
+  bin/linux/metar testfiles/image.dng > $dngOutputFile
+  if ! diff $dngOutputFile testfiles/$dngOutputFile >/dev/null 2>&1; then
+    echo "Invalid dng output."
+    exit
+  fi
+  rm $dngOutputFile
+}
 
 case $option in
   b)
@@ -177,14 +200,14 @@ case $option in
   t)
     testCmd
     ;;
-  clean)
-    cleanCmd
-    ;;
   docs)
     docsCmd
     ;;
   dot)
     dotCmd
+    ;;
+  ts)
+    sanityCmd
     ;;
   *)
 
@@ -193,6 +216,7 @@ b         Build the debug and release versions of metar.
 t         Test the debug and release versions of metar.
 docs      Build all the docs.
 dot       Build the dependency graph.
+ts        Run metar sanity checks.
 EOF
     ;;
 esac
